Task completed
Vedroid/jv-mate-dao3 pull request #1
Opened 2021-01-11 14:56 UTC by Vedroid

2021-01-11 16:40 UTC, IvanLuchkin approved these changes

2021-01-12 08:13 UTC, Sofasmile requested changes
good job

2021-01-12 08:13 UTC, Sofasmile commented on src/main/java/ua/vedroid/dao3/dao/ManufacturerDao.java
> +    List<Manufacturer> getAllManufacturers();
```suggestion
    List<Manufacturer> getAll();
```

2021-01-12 08:13 UTC, Sofasmile commented on src/main/java/ua/vedroid/dao3/dao/ManufacturerDaoImpl.java
> +        int index = Storage.manufacturers.indexOf(getById(manufacturer.getId()).orElseThrow());
```suggestion
        int index = Storage.manufacturers.indexOf(getById(manufacturer.getId()).get());
```

2021-01-12 08:13 UTC, Sofasmile commented on src/main/java/ua/vedroid/dao3/service/ManufacturerService.java
> +    List<Manufacturer> getAllManufacturers();
```suggestion
    List<Manufacturer> getAll();
```

2021-01-12 08:13 UTC, Sofasmile commented on src/main/java/ua/vedroid/dao3/service/ManufacturerServiceImpl.java
> +        return manufacturerDao.getById(manufacturerId).orElseThrow();
```suggestion
        return manufacturerDao.getById(manufacturerId).get();
```

2021-01-12 13:06 UTC, Sofasmile approved these changes

2021-01-12 14:46 UTC, merged