Task part2 completed
Vedroid/jv-mate-dao3 pull request #2
Opened 2021-01-12 15:09 UTC by Vedroid

2021-01-12 20:35 UTC, Mandybur800 approved these changes

2021-01-13 08:32 UTC, RomanDubovskyi requested changes

2021-01-13 08:32 UTC, RomanDubovskyi commented on src/main/java/ua/vedroid/dao3/service/CarServiceImpl.java
> +                .collect(Collectors.toList());
let's move this logic to the dao layer, when you connect db to the project you will write SQL query that will return sorter data from db

2021-01-13 11:13 UTC, RomanDubovskyi approved these changes

2021-01-13 13:10 UTC, merged