Completed dao8
Vedroid/jv-mate-dao3 pull request #7
Opened 2021-01-20 12:19 UTC by Vedroid

2021-01-20 12:41 UTC, Resci approved these changes

2021-01-21 10:06 UTC, dmytro-hryhoruk requested changes
Good job

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/java/ua/vedroid/dao3/controllers/DeleteDataController.java
> +        }
you definitely should not have SQL queries in controllers and I don't think that you should have such functionality accessible via an endpoint.  Imagine such an endpoint in the real project: 
https://rozetka.com.ua/ua/computers-notebooks/clear

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/java/ua/vedroid/dao3/controllers/car/AddDriversController.java
> +            }
let's just pass the whole exception as attributes and remove these conditions

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/java/ua/vedroid/dao3/controllers/driver/DeleteDriverController.java
> +        service.deleteById(Long.valueOf(req.getParameter("id")));
```suggestion
        service.deleteById(Long.valueOf(req.getParameter("driver_id")));
```

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/java/ua/vedroid/dao3/controllers/manufacturer/CreateManufacturerController.java
> +        String country = req.getParameter("country");
```suggestion
        String name = req.getParameter("manufacturer_name");
        String country = req.getParameter("manufacturer_country");
```

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/java/ua/vedroid/dao3/controllers/manufacturer/DeleteManufacturerController.java
> +        Long manufacturerId = Long.valueOf(req.getParameter("id"));
add model names to all parameters in all controllers

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/java/ua/vedroid/dao3/controllers/manufacturer/DeleteManufacturerController.java
> +        Long manufacturerId = Long.valueOf(req.getParameter("id"));
```suggestion
        Long manufacturerId = Long.valueOf(req.getParameter("manufacturer_id"));
```

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/views/cars/all.jsp
> +            <%--@elvariable id="cars" type="java.util.List"--%>
```suggestion
```

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/views/index.jsp
> +
```suggestion
```

2021-01-21 10:06 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/injectData</url-pattern>
```suggestion
        <url-pattern>/inject</url-pattern>
```

2021-01-21 10:52 UTC, Vedroid commented on src/main/java/ua/vedroid/dao3/controllers/car/AddDriversController.java
> +            }
@dmytro-hryhoruk
Так?
```
catch (NoSuchElementException ex) {
    req.setAttribute("msg", ex);
    req.getRequestDispatcher(ADD_DRIVER_JSP).forward(req, resp);
}
```
![image](https://user-images.githubusercontent.com/2052362/105341138-6aa98680-5be7-11eb-8f16-1c6b9ca601b8.png)

2021-01-21 15:44 UTC, dmytro-hryhoruk approved these changes

2021-01-24 10:50 UTC, merged